### ISSUE TITLE
Panic in middleware after ugprading to v1.14.0

### ISSUE THREAD

**Issue by coin-au-carre** [samber/slog-echo#32]
Have the following panic after upgrading from v1.12.7 to v1.14.
I am investigating not yet sure why it happened, but I let you know if I can find the reason since it is breaking my app on my side.

Edit: Upgrading to [v1.13.0](https://github.com/samber/slog-echo/releases/tag/v1.13.0) works fine for me I will not use v1.14 atm.

```
echo: http: panic serving [::1]:33510: runtime error: invalid memory address or nil pointer dereference
goroutine 100 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go/src/net/http/server.go:1898 +0xbe
panic({0x104b440?, 0x1c63580?})
        /usr/lib/go/src/runtime/panic.go:770 +0x132
ektos/core/server.slogEchoMiddleware.NewWithConfig.func1.1({0x1420ec0, 0xc0006b2140})
        /home/florian/go/pkg/mod/github.com/samber/slog-echo@v1.14.0/middleware.go:292 +0x28ce
github.com/labstack/echo/v4.(*Echo).ServeHTTP.func1({0x1420ec0, 0xc0006b2140})
        /home/florian/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:668 +0x127
ektos/web.NewServer.AddTrailingSlash.AddTrailingSlashWithConfig.func4.1({0x1420ec0, 0xc0006b2140})
        /home/florian/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/slash.go:69 +0x1af
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00019a248, {0x13fcf40, 0xc0006ec0e0}, 0xc0003367e0)
        /home/florian/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:674 +0x327
net/http.serverHandler.ServeHTTP({0xc0006d64b0?}, {0x13fcf40?, 0xc0006ec0e0?}, 0x6?)
        /usr/lib/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000410f30, {0x13ff838, 0xc0006d63c0})
        /usr/lib/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 99
        /usr/lib/go/src/net/http/server.go:3285 +0x4b4
```

**Comment by samber** [comment]
Damn! Sorry for this segfault.

-> v1.14.1
